
// Code generated by struct field builder; DO NOT EDIT.

package elsetype_eLWi9M5n

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
)

type ThirdPartyField interface {
	field.Field
	filter.BaseFilter[elsetype.ThirdParty]
	updater.BaseUpdater[elsetype.ThirdParty]
	TF() fields.Float64Field
	TmF() fields.IntegerField[elsetype.TimeType]
}

type ThirdPartyFieldInline interface {
	TF() fields.Float64Field
	TmF() fields.IntegerField[elsetype.TimeType]
}

type thirdPartyField struct {
	fields.BaseField[elsetype.ThirdParty]
}

var ThirdPartyDoc = NewThirdPartyField("")

func NewThirdPartyField(name string) ThirdPartyField {
	return &thirdPartyField{
		*fields.NewBaseField[elsetype.ThirdParty](name),
	}
}

func NewThirdPartyFieldInline(name string) ThirdPartyFieldInline {
	return &thirdPartyField{
		*fields.NewBaseField[elsetype.ThirdParty](name),
	}
}

func (s *thirdPartyField) TF() fields.Float64Field {
	return fields.NewFloat64Field(fields.SubField(s.FullName(), "t"))
}

func (s *thirdPartyField) TmF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "tm"))
}
