
// Code generated by go-mongodb-gen; DO NOT EDIT.

package elsetype_eLWi9M5n

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
)

type LikeThirdPartyField[T any] interface {
	field.Field
	filter.BaseFilter[T]
	updater.BaseUpdater[T]

	LikeThirdPartyFieldSubFields
}

type ThirdPartyField = LikeThirdPartyField[elsetype.ThirdParty]

type LikeThirdPartyFieldSubFields interface {
	Float64F() fields.Float64Field
	LikeInt_TimeTypeF() fields.IntegerField[elsetype.TimeType]
}

type likeThirdPartyField[T any] struct {
	fields.BaseField[T]
}

func NewLikeThirdPartyField[T any](name string) LikeThirdPartyField[T] {
	return &likeThirdPartyField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewThirdPartyField = NewLikeThirdPartyField[elsetype.ThirdParty]

func NewLikeThirdPartyFieldSubFields(name string) LikeThirdPartyFieldSubFields {
	return &likeThirdPartyField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewThirdPartyFieldSubFields = NewLikeThirdPartyFieldSubFields

var ThirdPartyColl = struct{
	DefaultName string
	LikeThirdPartyFieldSubFields
}{ "ThirdParty", NewThirdPartyFieldSubFields("")}

func (s *likeThirdPartyField[T]) Float64F() fields.Float64Field {
	return fields.NewFloat64Field(fields.SubField(s.FullName(), "float64"))
}

func (s *likeThirdPartyField[T]) LikeInt_TimeTypeF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "likeint_timetype"))
}
