
// Code generated by struct field builder; DO NOT EDIT.

package base

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
)

type OrderField interface {
	field.Field
	filter.ComparableFilter[Order]
	updater.BaseUpdater[Order]
	Uint64F() fields.Uint64Field
	StringF() fields.StringField
	LikeInt_elsetype_TimeTypeF() fields.IntegerField[elsetype.TimeType]
	LikeUint_elsetype_UTimeF() fields.UnIntegerField[elsetype.UTime, int]
}

type OrderFieldInline interface {
	Uint64F() fields.Uint64Field
	StringF() fields.StringField
	LikeInt_elsetype_TimeTypeF() fields.IntegerField[elsetype.TimeType]
	LikeUint_elsetype_UTimeF() fields.UnIntegerField[elsetype.UTime, int]
}

type orderField struct {
	fields.BaseField[Order]
}

var OrderDoc = NewOrderField("")

func NewOrderField(name string) OrderField {
	return &orderField{
		*fields.NewBaseField[Order](name),
	}
}

func NewOrderFieldInline(name string) OrderFieldInline {
	return &orderField{
		*fields.NewBaseField[Order](name),
	}
}

func (s *orderField) Uint64F() fields.Uint64Field {
	return fields.NewUint64Field(fields.SubField(s.FullName(), "uint64"))
}

func (s *orderField) StringF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "string"))
}

func (s *orderField) LikeInt_elsetype_TimeTypeF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "likeint_elsetype_timetype"))
}

func (s *orderField) LikeUint_elsetype_UTimeF() fields.UnIntegerField[elsetype.UTime, int] {
	return fields.NewUnIntegerField[elsetype.UTime, int](fields.SubField(s.FullName(), "likeuint_elsetype_utime"))
}
