
// Code generated by struct field builder; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  bson_YR4jowyB "github.com/xpwu/go-mongodb/fields/structfieldbuilder_demo/userinfo/bson_YR4jowyB"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  bson "go.mongodb.org/mongo-driver/v2/bson"
)

type UserInfoField interface {
	field.Field
	filter.BaseFilter[UserInfo]
	updater.BaseUpdater[UserInfo]
	StringIDF() fields.StringField
	IntLoginF() fields.IntField
	IntArrayPassF() fields.ArrayComparableField[int, fields.IntField]
	WxPtrF() WxField
	WxF() WxField
	WsArrayF() fields.ArrayField[Wx, WxField]
	Int16Array2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]]
	LikeFloat64_GPSF() fields.ComputableField[GPS]
	BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
}

type UserInfoFieldInline interface {
	StringIDF() fields.StringField
	IntLoginF() fields.IntField
	IntArrayPassF() fields.ArrayComparableField[int, fields.IntField]
	WxPtrF() WxField
	WxF() WxField
	WsArrayF() fields.ArrayField[Wx, WxField]
	Int16Array2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]]
	LikeFloat64_GPSF() fields.ComputableField[GPS]
	BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
}

type userInfoField struct {
	fields.BaseField[UserInfo]
}

var UserInfoDoc = NewUserInfoField("")

func NewUserInfoField(name string) UserInfoField {
	return &userInfoField{
		*fields.NewBaseField[UserInfo](name),
	}
}

func NewUserInfoFieldInline(name string) UserInfoFieldInline {
	return &userInfoField{
		*fields.NewBaseField[UserInfo](name),
	}
}

func (s *userInfoField) StringIDF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "_id"))
}

func (s *userInfoField) IntLoginF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "Login"))
}

func (s *userInfoField) IntArrayPassF() fields.ArrayComparableField[int, fields.IntField] {
	return func(name string) fields.ArrayComparableField[int, fields.IntField] {
			newElem := fields.NewIntField
			return fields.NewArrayAnyComparableField[int, fields.IntField](name, newElem)
		}(fields.SubField(s.FullName(), "intarraypass"))
}

func (s *userInfoField) WxPtrF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wxptr"))
}

func (s *userInfoField) WxF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wx"))
}

func (s *userInfoField) WsArrayF() fields.ArrayField[Wx, WxField] {
	return func(name string) fields.ArrayField[Wx, WxField] {
			newElem := NewWxField
			return fields.NewArrayField[Wx, WxField](name, newElem)
		}(fields.SubField(s.FullName(), "wsarray"))
}

func (s *userInfoField) Int16Array2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
	return func(name string) fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
			newElem := func(name string) fields.ArrayComparableField[int16, fields.Int16Field] {
				newElem := fields.NewInt16Field
				return fields.NewArrayAnyComparableField[int16, fields.Int16Field](name, newElem)
			}
			return fields.NewArrayAnyComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]](name, newElem)
		}(fields.SubField(s.FullName(), "int16array2"))
}

func (s *userInfoField) LikeFloat64_GPSF() fields.ComputableField[GPS] {
	return fields.NewComputableField[GPS](fields.SubField(s.FullName(), "likefloat64_gps"))
}

func (s *userInfoField) BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "bsond"))
}
