
// Code generated by struct field builder; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  elsetype "github.com/xpwu/go-mongodb/fields/structfieldbuilder_demo/elsetype"
  base "github.com/xpwu/go-mongodb/fields/structfieldbuilder_demo/userinfo/base"
  elsetype_9cYkCYSO "github.com/xpwu/go-mongodb/fields/structfieldbuilder_demo/userinfo/elsetype_9cYkCYSO"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
)

type WxField interface {
	field.Field
	filter.BaseFilter[Wx]
	updater.BaseUpdater[Wx]
	Decimal128F() fields.Decimal128Field
	IntPtrF() fields.IntField
	OrderF() base.OrderField
	ThirdPartyF() elsetype_9cYkCYSO.ThirdPartyField
	SpherePointF() fields.SpherePointField
	FlatPointF() fields.FlatPointField
	LikeStringName_elsetype_FullNameF() fields.LikeStringField[elsetype.FullName]
}

type WxFieldInline interface {
	Decimal128F() fields.Decimal128Field
	IntPtrF() fields.IntField
	OrderF() base.OrderField
	ThirdPartyF() elsetype_9cYkCYSO.ThirdPartyField
	SpherePointF() fields.SpherePointField
	FlatPointF() fields.FlatPointField
	LikeStringName_elsetype_FullNameF() fields.LikeStringField[elsetype.FullName]
}

type wxField struct {
	fields.BaseField[Wx]
}

var WxDoc = NewWxField("")

func NewWxField(name string) WxField {
	return &wxField{
		*fields.NewBaseField[Wx](name),
	}
}

func NewWxFieldInline(name string) WxFieldInline {
	return &wxField{
		*fields.NewBaseField[Wx](name),
	}
}

func (s *wxField) Decimal128F() fields.Decimal128Field {
	return fields.NewDecimal128Field(fields.SubField(s.FullName(), "decimal128"))
}

func (s *wxField) IntPtrF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "intptr"))
}

func (s *wxField) OrderF() base.OrderField {
	return base.NewOrderField(fields.SubField(s.FullName(), "order"))
}

func (s *wxField) ThirdPartyF() elsetype_9cYkCYSO.ThirdPartyField {
	return elsetype_9cYkCYSO.NewThirdPartyField(fields.SubField(s.FullName(), "thirdparty"))
}

func (s *wxField) SpherePointF() fields.SpherePointField {
	return fields.NewSpherePointField(fields.SubField(s.FullName(), "spherepoint"))
}

func (s *wxField) FlatPointF() fields.FlatPointField {
	return fields.NewFlatPointField(fields.SubField(s.FullName(), "flatpoint"))
}

func (s *wxField) LikeStringName_elsetype_FullNameF() fields.LikeStringField[elsetype.FullName] {
	return fields.NewLikeStringField[elsetype.FullName](fields.SubField(s.FullName(), "likestringname_elsetype_fullname"))
}
