
// Code generated by struct field builder; DO NOT EDIT.

package elsetype_9cYkCYSO

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  elsetype "github.com/xpwu/go-mongodb/fields/structfieldbuilder_demo/elsetype"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
)

type ThirdPartyField interface {
	field.Field
	filter.BaseFilter[elsetype.ThirdParty]
	updater.BaseUpdater[elsetype.ThirdParty]
	Float64F() fields.Float64Field
	LikeInt_TimeTypeF() fields.IntegerField[elsetype.TimeType]
}

type ThirdPartyFieldInline interface {
	Float64F() fields.Float64Field
	LikeInt_TimeTypeF() fields.IntegerField[elsetype.TimeType]
}

type thirdPartyField struct {
	fields.BaseField[elsetype.ThirdParty]
}

var ThirdPartyDoc = NewThirdPartyField("")

func NewThirdPartyField(name string) ThirdPartyField {
	return &thirdPartyField{
		*fields.NewBaseField[elsetype.ThirdParty](name),
	}
}

func NewThirdPartyFieldInline(name string) ThirdPartyFieldInline {
	return &thirdPartyField{
		*fields.NewBaseField[elsetype.ThirdParty](name),
	}
}

func (s *thirdPartyField) Float64F() fields.Float64Field {
	return fields.NewFloat64Field(fields.SubField(s.FullName(), "float64"))
}

func (s *thirdPartyField) LikeInt_TimeTypeF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "likeint_timetype"))
}
