
// Code generated by struct field builder; DO NOT EDIT.

package bson_YR4jowyB

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  bson "go.mongodb.org/mongo-driver/v2/bson"
)

type EField interface {
	field.Field
	filter.BaseFilter[bson.E]
	updater.BaseUpdater[bson.E]
	KeyF() fields.StringField
	ValueF() fields.BaseStructField[any]
}

type EFieldInline interface {
	KeyF() fields.StringField
	ValueF() fields.BaseStructField[any]
}

type eField struct {
	fields.BaseField[bson.E]
}

var EDoc = NewEField("")

func NewEField(name string) EField {
	return &eField{
		*fields.NewBaseField[bson.E](name),
	}
}

func NewEFieldInline(name string) EFieldInline {
	return &eField{
		*fields.NewBaseField[bson.E](name),
	}
}

func (s *eField) KeyF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "key"))
}

func (s *eField) ValueF() fields.BaseStructField[any] {
	return fields.NewBaseStructField[any](fields.SubField(s.FullName(), "value"))
}
