
// Code generated by go-mongodb-gen; DO NOT EDIT.

package bson_YR4jowyB

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  bson "go.mongodb.org/mongo-driver/v2/bson"
)

type LikeEField[T any] interface {
	field.Field
	filter.BaseFilter[T]
	updater.BaseUpdater[T]

	LikeEFieldSubFields
}

type EField = LikeEField[bson.E]

type LikeEFieldSubFields interface {
	KeyF() fields.StringField
	ValueF() fields.BaseStructField[any]
}

type likeEField[T any] struct {
	fields.BaseField[T]
}

func NewLikeEField[T any](name string) LikeEField[T] {
	return &likeEField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewEField = NewLikeEField[bson.E]

func NewLikeEFieldSubFields(name string) LikeEFieldSubFields {
	return &likeEField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewEFieldSubFields = NewLikeEFieldSubFields

var EColl = struct{
	DefaultName string
	LikeEFieldSubFields
}{ "E", NewEFieldSubFields("")}

func (s *likeEField[T]) KeyF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "key"))
}

func (s *likeEField[T]) ValueF() fields.BaseStructField[any] {
	return fields.NewBaseStructField[any](fields.SubField(s.FullName(), "value"))
}
