
// Code generated by go-mongodb-gen; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
)

type LikeOrgInfoField[T any] interface {
	field.Field
	filter.BaseFilter[T]
	updater.BaseUpdater[T]

	LikeOrgInfoFieldSubFields
}

type OrgInfoField = LikeOrgInfoField[OrgInfo]

type LikeOrgInfoFieldSubFields interface {
	AdminF() UserInfoField
}

type likeOrgInfoField[T any] struct {
	fields.BaseField[T]
}

func NewLikeOrgInfoField[T any](name string) LikeOrgInfoField[T] {
	return &likeOrgInfoField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewOrgInfoField = NewLikeOrgInfoField[OrgInfo]

func NewLikeOrgInfoFieldSubFields(name string) LikeOrgInfoFieldSubFields {
	return &likeOrgInfoField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewOrgInfoFieldSubFields = NewLikeOrgInfoFieldSubFields

var OrgInfoColl = struct{
	DefaultName string
	LikeOrgInfoFieldSubFields
}{ "OrgInfo", NewOrgInfoFieldSubFields("")}

func (s *likeOrgInfoField[T]) AdminF() UserInfoField {
	return NewUserInfoField(fields.SubField(s.FullName(), "admin"))
}
