
// Code generated by go-mongodb-gen; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  bson_YR4jowyB "github.com/xpwu/go-mongodb/zdemo/userinfo/bson_YR4jowyB"
  bson "go.mongodb.org/mongo-driver/v2/bson"
)

type UserInfoField interface {
	field.Field
	filter.BaseFilter[UserInfo]
	updater.BaseUpdater[UserInfo]
	IDF() fields.StringField
	LoginF() fields.IntField
	PassF() fields.ArrayComparableField[int, fields.IntField]
	WxF() WxField
	Wx3F() WxField
	WsF() fields.ArrayField[Wx, WxField]
	Pass2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]]
	GpsF() fields.ComputableField[GPS]
	GpsesF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	GpsesAF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	BSON_DF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	WxFieldInline
}

type UserInfoFieldInline interface {
	IDF() fields.StringField
	LoginF() fields.IntField
	PassF() fields.ArrayComparableField[int, fields.IntField]
	WxF() WxField
	Wx3F() WxField
	WsF() fields.ArrayField[Wx, WxField]
	Pass2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]]
	GpsF() fields.ComputableField[GPS]
	GpsesF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	GpsesAF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	BSON_DF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	WxFieldInline
}

type userInfoField struct {
	fields.BaseField[UserInfo]
	WxFieldInline
}

var UserInfoDoc = NewUserInfoField("")

func NewUserInfoField(name string) UserInfoField {
	return &userInfoField{
		*fields.NewBaseField[UserInfo](name),
		NewWxFieldInline(name),
	}
}

func NewUserInfoFieldInline(name string) UserInfoFieldInline {
	return &userInfoField{
		*fields.NewBaseField[UserInfo](name),
		NewWxFieldInline(name),
	}
}

func (s *userInfoField) IDF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "_id"))
}

func (s *userInfoField) LoginF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "Login"))
}

func (s *userInfoField) PassF() fields.ArrayComparableField[int, fields.IntField] {
	return func(name string) fields.ArrayComparableField[int, fields.IntField] {
			newElem := fields.NewIntField
			return fields.NewArrayAnyComparableField[int, fields.IntField](name, newElem)
		}(fields.SubField(s.FullName(), "pass"))
}

func (s *userInfoField) WxF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wx"))
}

func (s *userInfoField) Wx3F() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wx3"))
}

func (s *userInfoField) WsF() fields.ArrayField[Wx, WxField] {
	return func(name string) fields.ArrayField[Wx, WxField] {
			newElem := NewWxField
			return fields.NewArrayField[Wx, WxField](name, newElem)
		}(fields.SubField(s.FullName(), "ws"))
}

func (s *userInfoField) Pass2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
	return func(name string) fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
			newElem := func(name string) fields.ArrayComparableField[int16, fields.Int16Field] {
				newElem := fields.NewInt16Field
				return fields.NewArrayAnyComparableField[int16, fields.Int16Field](name, newElem)
			}
			return fields.NewArrayAnyComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]](name, newElem)
		}(fields.SubField(s.FullName(), "pass2"))
}

func (s *userInfoField) GpsF() fields.ComputableField[GPS] {
	return fields.NewComputableField[GPS](fields.SubField(s.FullName(), "gps"))
}

func (s *userInfoField) GpsesF() fields.ArrayField[GPS, fields.ComputableField[GPS]] {
	return func(name string) fields.ArrayField[GPS, fields.ComputableField[GPS]] {
			newElem := fields.NewComputableField[GPS]
			return fields.NewArrayField[GPS, fields.ComputableField[GPS]](name, newElem)
		}(fields.SubField(s.FullName(), "gpses"))
}

func (s *userInfoField) GpsesAF() fields.ArrayField[GPS, fields.ComputableField[GPS]] {
	return func(name string) fields.ArrayField[GPS, fields.ComputableField[GPS]] {
			newElem := fields.NewComputableField[GPS]
			return fields.NewArrayField[GPS, fields.ComputableField[GPS]](name, newElem)
		}(fields.SubField(s.FullName(), "gpsesa"))
}

func (s *userInfoField) BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "bsond"))
}

func (s *userInfoField) BSON_DF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "bson_d"))
}
