
// Code generated by go-mongodb-gen; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  bson_YR4jowyB "github.com/xpwu/go-mongodb/zdemo/userinfo/bson_YR4jowyB"
  bson "go.mongodb.org/mongo-driver/v2/bson"
)

type LikeUserInfoField[T any] interface {
	field.Field
	filter.BaseFilter[T]
	updater.BaseUpdater[T]

	LikeUserInfoFieldSubFields
}

type UserInfoField = LikeUserInfoField[UserInfo]

type LikeUserInfoFieldSubFields interface {
	StringIDF() fields.StringField
	IntLoginF() fields.IntField
	IntArrayPassF() fields.ArrayComparableField[int, fields.IntField]
	WxPtrF() WxField
	WxF() WxField
	WsArrayF() fields.ArrayField[Wx, WxField]
	Int16Array2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]]
	LikeFloat64_GPSF() fields.ComputableField[GPS]
	LikeFloat64Array_GPSesF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	AliasGPSesF() fields.ArrayField[GPS, fields.ComputableField[GPS]]
	BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	AliasDefAEF() bson_YR4jowyB.LikeEField[DefAE]
	AalisBsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	AalisBsonDDefF() fields.ArrayField[bson.E, bson_YR4jowyB.EField]
	AliasWxF() WxField
	LikeWx_WxDefF() LikeWxField[WxDef]
	DefAliasWx_WXDef2F() LikeWxField[WXDef2]
	ByteF() fields.ByteField
	BytesF() fields.ArrayComparableField[byte, fields.ByteField]
	RuneF() fields.RuneField
	RunesF() fields.ArrayComparableField[rune, fields.RuneField]
	LikeWxFieldSubFields
}

type likeUserInfoField[T any] struct {
	fields.BaseField[T]
	LikeWxFieldSubFields
}

func NewLikeUserInfoField[T any](name string) LikeUserInfoField[T] {
	return &likeUserInfoField[T]{
		*fields.NewBaseField[T](name),
		NewLikeWxFieldSubFields(name),
	}
}

var NewUserInfoField = NewLikeUserInfoField[UserInfo]

func NewLikeUserInfoFieldSubFields(name string) LikeUserInfoFieldSubFields {
	return &likeUserInfoField[any]{
		*fields.NewBaseField[any](name),
		NewLikeWxFieldSubFields(name),
	}
}

var NewUserInfoFieldSubFields = NewLikeUserInfoFieldSubFields

var UserInfoColl = struct{
	DefaultName string
	LikeUserInfoFieldSubFields
}{ "UserInfo", NewUserInfoFieldSubFields("")}

func (s *likeUserInfoField[T]) StringIDF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "_id"))
}

func (s *likeUserInfoField[T]) IntLoginF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "Login"))
}

func (s *likeUserInfoField[T]) IntArrayPassF() fields.ArrayComparableField[int, fields.IntField] {
	return func(name string) fields.ArrayComparableField[int, fields.IntField] {
			newElem := fields.NewIntField
			return fields.NewArrayAnyComparableField[int, fields.IntField](name, newElem)
		}(fields.SubField(s.FullName(), "intarraypass"))
}

func (s *likeUserInfoField[T]) WxPtrF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wxptr"))
}

func (s *likeUserInfoField[T]) WxF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "wx"))
}

func (s *likeUserInfoField[T]) WsArrayF() fields.ArrayField[Wx, WxField] {
	return func(name string) fields.ArrayField[Wx, WxField] {
			newElem := NewWxField
			return fields.NewArrayField[Wx, WxField](name, newElem)
		}(fields.SubField(s.FullName(), "wsarray"))
}

func (s *likeUserInfoField[T]) Int16Array2F() fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
	return func(name string) fields.ArrayComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]] {
			newElem := func(name string) fields.ArrayComparableField[int16, fields.Int16Field] {
				newElem := fields.NewInt16Field
				return fields.NewArrayAnyComparableField[int16, fields.Int16Field](name, newElem)
			}
			return fields.NewArrayAnyComparableField[[]int16, fields.ArrayComparableField[int16, fields.Int16Field]](name, newElem)
		}(fields.SubField(s.FullName(), "int16array2"))
}

func (s *likeUserInfoField[T]) LikeFloat64_GPSF() fields.ComputableField[GPS] {
	return fields.NewComputableField[GPS](fields.SubField(s.FullName(), "likefloat64_gps"))
}

func (s *likeUserInfoField[T]) LikeFloat64Array_GPSesF() fields.ArrayField[GPS, fields.ComputableField[GPS]] {
	return func(name string) fields.ArrayField[GPS, fields.ComputableField[GPS]] {
			newElem := fields.NewComputableField[GPS]
			return fields.NewArrayField[GPS, fields.ComputableField[GPS]](name, newElem)
		}(fields.SubField(s.FullName(), "likefloat64array_gpses"))
}

func (s *likeUserInfoField[T]) AliasGPSesF() fields.ArrayField[GPS, fields.ComputableField[GPS]] {
	return func(name string) fields.ArrayField[GPS, fields.ComputableField[GPS]] {
			newElem := fields.NewComputableField[GPS]
			return fields.NewArrayField[GPS, fields.ComputableField[GPS]](name, newElem)
		}(fields.SubField(s.FullName(), "aliasgpses"))
}

func (s *likeUserInfoField[T]) BsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "bsond"))
}

func (s *likeUserInfoField[T]) AliasDefAEF() bson_YR4jowyB.LikeEField[DefAE] {
	return bson_YR4jowyB.NewLikeEField[DefAE](fields.SubField(s.FullName(), "aliasdefae"))
}

func (s *likeUserInfoField[T]) AalisBsonDF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "aalisbsond"))
}

func (s *likeUserInfoField[T]) AalisBsonDDefF() fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
	return func(name string) fields.ArrayField[bson.E, bson_YR4jowyB.EField] {
			newElem := bson_YR4jowyB.NewEField
			return fields.NewArrayField[bson.E, bson_YR4jowyB.EField](name, newElem)
		}(fields.SubField(s.FullName(), "aalisbsonddef"))
}

func (s *likeUserInfoField[T]) AliasWxF() WxField {
	return NewWxField(fields.SubField(s.FullName(), "aliaswx"))
}

func (s *likeUserInfoField[T]) LikeWx_WxDefF() LikeWxField[WxDef] {
	return NewLikeWxField[WxDef](fields.SubField(s.FullName(), "likewx_wxdef"))
}

func (s *likeUserInfoField[T]) DefAliasWx_WXDef2F() LikeWxField[WXDef2] {
	return NewLikeWxField[WXDef2](fields.SubField(s.FullName(), "defaliaswx_wxdef2"))
}

func (s *likeUserInfoField[T]) ByteF() fields.ByteField {
	return fields.NewByteField(fields.SubField(s.FullName(), "byte"))
}

func (s *likeUserInfoField[T]) BytesF() fields.ArrayComparableField[byte, fields.ByteField] {
	return func(name string) fields.ArrayComparableField[byte, fields.ByteField] {
			newElem := fields.NewByteField
			return fields.NewArrayAnyComparableField[byte, fields.ByteField](name, newElem)
		}(fields.SubField(s.FullName(), "bytes"))
}

func (s *likeUserInfoField[T]) RuneF() fields.RuneField {
	return fields.NewRuneField(fields.SubField(s.FullName(), "rune"))
}

func (s *likeUserInfoField[T]) RunesF() fields.ArrayComparableField[rune, fields.RuneField] {
	return func(name string) fields.ArrayComparableField[rune, fields.RuneField] {
			newElem := fields.NewRuneField
			return fields.NewArrayAnyComparableField[rune, fields.RuneField](name, newElem)
		}(fields.SubField(s.FullName(), "runes"))
}
