
// Code generated by struct field builder; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
  base "github.com/xpwu/go-mongodb/zdemo/userinfo/base"
  elsetype_eLWi9M5n "github.com/xpwu/go-mongodb/zdemo/userinfo/elsetype_eLWi9M5n"
)

type WxField interface {
	field.Field
	filter.ComparableFilter[Wx]
	updater.BaseUpdater[Wx]
	AgeF() fields.Decimal128Field
	TimeF() fields.IntField
	OrderF() base.OrderField
	ThirdF() elsetype_eLWi9M5n.ThirdPartyField
	AddrF() fields.SpherePointField
	PlayerF() fields.FlatPointField
	NameF() fields.LikeStringField[elsetype.FullName]
}

type WxFieldInline interface {
	AgeF() fields.Decimal128Field
	TimeF() fields.IntField
	OrderF() base.OrderField
	ThirdF() elsetype_eLWi9M5n.ThirdPartyField
	AddrF() fields.SpherePointField
	PlayerF() fields.FlatPointField
	NameF() fields.LikeStringField[elsetype.FullName]
}

type wxField struct {
	fields.BaseField[Wx]
}

var WxDoc = NewWxField("")

func NewWxField(name string) WxField {
	return &wxField{
		*fields.NewBaseField[Wx](name),
	}
}

func NewWxFieldInline(name string) WxFieldInline {
	return &wxField{
		*fields.NewBaseField[Wx](name),
	}
}

func (s *wxField) AgeF() fields.Decimal128Field {
	return fields.NewDecimal128Field(fields.SubField(s.FullName(), "age"))
}

func (s *wxField) TimeF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "time"))
}

func (s *wxField) OrderF() base.OrderField {
	return base.NewOrderField(fields.SubField(s.FullName(), "order"))
}

func (s *wxField) ThirdF() elsetype_eLWi9M5n.ThirdPartyField {
	return elsetype_eLWi9M5n.NewThirdPartyField(fields.SubField(s.FullName(), "third"))
}

func (s *wxField) AddrF() fields.SpherePointField {
	return fields.NewSpherePointField(fields.SubField(s.FullName(), "addr"))
}

func (s *wxField) PlayerF() fields.FlatPointField {
	return fields.NewFlatPointField(fields.SubField(s.FullName(), "player"))
}

func (s *wxField) NameF() fields.LikeStringField[elsetype.FullName] {
	return fields.NewLikeStringField[elsetype.FullName](fields.SubField(s.FullName(), "name"))
}
