
// Code generated by go-mongodb-gen; DO NOT EDIT.

package userinfo

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
  base "github.com/xpwu/go-mongodb/zdemo/userinfo/base"
  elsetype_eLWi9M5n "github.com/xpwu/go-mongodb/zdemo/userinfo/elsetype_eLWi9M5n"
)

type LikeWxField[T any] interface {
	field.Field
	filter.BaseFilter[T]
	updater.BaseUpdater[T]

	LikeWxFieldSubFields
}

type WxField = LikeWxField[Wx]

type LikeWxFieldSubFields interface {
	Decimal128F() fields.Decimal128Field
	IntPtrF() fields.IntField
	OrderF() base.OrderField
	ThirdPartyF() elsetype_eLWi9M5n.ThirdPartyField
	SpherePointF() fields.SpherePointField
	FlatPointF() fields.FlatPointField
	LikeStringName_elsetype_FullNameF() fields.LikeStringField[elsetype.FullName]
}

type likeWxField[T any] struct {
	fields.BaseField[T]
}

func NewLikeWxField[T any](name string) LikeWxField[T] {
	return &likeWxField[T]{
		*fields.NewBaseField[T](name),
	}
}

var WxDoc = NewWxField("")
var NewWxField = NewLikeWxField[Wx]

func NewLikeWxFieldSubFields(name string) LikeWxFieldSubFields {
	return &likeWxField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewWxFieldSubFields = NewLikeWxFieldSubFields

func (s *likeWxField[T]) Decimal128F() fields.Decimal128Field {
	return fields.NewDecimal128Field(fields.SubField(s.FullName(), "decimal128"))
}

func (s *likeWxField[T]) IntPtrF() fields.IntField {
	return fields.NewIntField(fields.SubField(s.FullName(), "intptr"))
}

func (s *likeWxField[T]) OrderF() base.OrderField {
	return base.NewOrderField(fields.SubField(s.FullName(), "order"))
}

func (s *likeWxField[T]) ThirdPartyF() elsetype_eLWi9M5n.ThirdPartyField {
	return elsetype_eLWi9M5n.NewThirdPartyField(fields.SubField(s.FullName(), "thirdparty"))
}

func (s *likeWxField[T]) SpherePointF() fields.SpherePointField {
	return fields.NewSpherePointField(fields.SubField(s.FullName(), "spherepoint"))
}

func (s *likeWxField[T]) FlatPointF() fields.FlatPointField {
	return fields.NewFlatPointField(fields.SubField(s.FullName(), "flatpoint"))
}

func (s *likeWxField[T]) LikeStringName_elsetype_FullNameF() fields.LikeStringField[elsetype.FullName] {
	return fields.NewLikeStringField[elsetype.FullName](fields.SubField(s.FullName(), "likestringname_elsetype_fullname"))
}
