
// Code generated by go-mongodb-gen; DO NOT EDIT.

package base

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
)

type LikeOrderField[T any] interface {
	field.Field
	filter.ComparableFilter[T]
	updater.BaseUpdater[T]

	LikeOrderFieldSubFields
}

type OrderField = LikeOrderField[Order]

type LikeOrderFieldSubFields interface {
	Uint64F() fields.Uint64Field
	StringF() fields.StringField
	LikeInt_elsetype_TimeTypeF() fields.IntegerField[elsetype.TimeType]
	LikeUint_elsetype_UTimeF() fields.UnIntegerField[elsetype.UTime, int]
}

type likeOrderField[T any] struct {
	fields.BaseField[T]
}

func NewLikeOrderField[T any](name string) LikeOrderField[T] {
	return &likeOrderField[T]{
		*fields.NewBaseField[T](name),
	}
}

var NewOrderField = NewLikeOrderField[Order]

func NewLikeOrderFieldSubFields(name string) LikeOrderFieldSubFields {
	return &likeOrderField[any]{
		*fields.NewBaseField[any](name),
	}
}

var NewOrderFieldSubFields = NewLikeOrderFieldSubFields

var OrderColl = struct{
	DefaultName string
	LikeOrderFieldSubFields
}{ "Order", NewOrderFieldSubFields("")}

func (s *likeOrderField[T]) Uint64F() fields.Uint64Field {
	return fields.NewUint64Field(fields.SubField(s.FullName(), "uint64"))
}

func (s *likeOrderField[T]) StringF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "string"))
}

func (s *likeOrderField[T]) LikeInt_elsetype_TimeTypeF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "likeint_elsetype_timetype"))
}

func (s *likeOrderField[T]) LikeUint_elsetype_UTimeF() fields.UnIntegerField[elsetype.UTime, int] {
	return fields.NewUnIntegerField[elsetype.UTime, int](fields.SubField(s.FullName(), "likeuint_elsetype_utime"))
}
