
// Code generated by go-mongodb-gen; DO NOT EDIT.

package base

import (
  field "github.com/xpwu/go-mongodb/field"
  fields "github.com/xpwu/go-mongodb/fields"
  filter "github.com/xpwu/go-mongodb/filter"
  updater "github.com/xpwu/go-mongodb/updater"
  elsetype "github.com/xpwu/go-mongodb/zdemo/elsetype"
)

type OrderField interface {
	field.Field
	filter.ComparableFilter[Order]
	updater.BaseUpdater[Order]
	TimeF() fields.Uint64Field
	ProcessorF() fields.StringField
	AgeF() fields.IntegerField[elsetype.TimeType]
	HourF() fields.UnIntegerField[elsetype.UTime, int]
}

type OrderFieldInline interface {
	TimeF() fields.Uint64Field
	ProcessorF() fields.StringField
	AgeF() fields.IntegerField[elsetype.TimeType]
	HourF() fields.UnIntegerField[elsetype.UTime, int]
}

type orderField struct {
	fields.BaseField[Order]
}

var OrderDoc = NewOrderField("")

func NewOrderField(name string) OrderField {
	return &orderField{
		*fields.NewBaseField[Order](name),
	}
}

func NewOrderFieldInline(name string) OrderFieldInline {
	return &orderField{
		*fields.NewBaseField[Order](name),
	}
}

func (s *orderField) TimeF() fields.Uint64Field {
	return fields.NewUint64Field(fields.SubField(s.FullName(), "time"))
}

func (s *orderField) ProcessorF() fields.StringField {
	return fields.NewStringField(fields.SubField(s.FullName(), "processor"))
}

func (s *orderField) AgeF() fields.IntegerField[elsetype.TimeType] {
	return fields.NewIntegerField[elsetype.TimeType](fields.SubField(s.FullName(), "age"))
}

func (s *orderField) HourF() fields.UnIntegerField[elsetype.UTime, int] {
	return fields.NewUnIntegerField[elsetype.UTime, int](fields.SubField(s.FullName(), "hour"))
}
